language : node
sudo: true
branches:
  only:
  - "/^.*master$/"
  - "/^ *staging$/"
node:
- '0.12'
script : 
# - "script/install && script/start && script/test && script/db && script/stop"
  - "script/db"
